import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pokerbaazi Live - Baazi Games</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
      </Head>
      <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
      <script>AOS.init();</script>
      {/* header start   */}
      <header>
        <img
          loading="lazy"
          id={styles.pbLogo}
          src="https://pokerbaazilive.com/wp-content/uploads/2021/05/PB_Live_Website.png"
          alt="PB_Live_Logo_White"
        />
        <div className={styles.blContainer}>
          <img
            id={styles.blLogo}
            className={styles.logo}
            src="	https://pokerbaazilive.com/wp-content/uploads/2021/05/PB_Live_Website_Black.png"
            alt="PB_Live_Logo_Black"
          />
        </div>
      </header>
      {/* header end   */}

      {/* main content start here    */}
      <section>
        <div className={styles.hmSlider}>
          <div className={styles.container}>
            <div className={styles.hmSlider__content}>
              <h2 className={styles.hmSlider__h2}>
                Welcome to the
                <span className={styles.hmSlider__span}>Live Game</span>
              </h2>
              <h1 className={styles.hmSlider__h1}>
                Take a
                <br />
                Seat{" "}
                <span style={{ color: "#EE0034", marginLeft: "-15px" }}>!</span>
              </h1>
              <p className={styles.hmSlider__p} style={{ color: "white" }}>
                India's most trusted online poker site is now making waves in
                live poker. We are thrilled to extend a warm welcome to all
                players who wish to enjoy the game in its most iconic form.
              </p>
            </div>
          </div>
        </div>

        {/* mid content i frame and all */}
        <div
          data-aos="fade-up"
          data-aos-duration="3000"
          className={styles.background_container}
        >
          <div className={styles.container}>
            <div className={styles.iframe__container}>
              <div className={styles.iframeClass}>
                <iframe
                  id={styles.iframeId}
                  width="560"
                  height="315"
                  src="https://www.youtube.com/embed/b9joPv6PYjk"
                  title="YouTube video player"
                  frameborder="0"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                  allowfullscreen
                ></iframe>
              </div>
              <div className={styles.content}>
                <h3 className={styles.h3}>
                  How to play poker <span style={{ color: "#f03734" }}>?</span>
                </h3>
                <div className={styles.line}></div>
                <div className={styles.paragraph__container}>
                  <p className={styles.paragraph}>
                    Get started on the right note with our exclusive video on
                    ‘how to play poker.’ Developed with the help of some of the
                    best card players in our country, this video is here to run
                    you through the basic rules and strategies, and would also
                    offer exclusive insights on how you can build your game up
                    from zero.
                  </p>
                  <p className={styles.paragraph}>
                    Click the play button to get started with our exclusive
                    video poker trainer now:
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* main content ended here    */}

      {/* footer start here */}
      <footer>
        <div className={styles.footer__container}>
          <div className={styles.container}>
            <img
              id={styles.footer__logo__img}
              className={styles.footer__logo}
              src="https://pokerbaazilive.com/wp-content/uploads/2021/05/PB_Live_Website.png"
            />
            <br />
            <br />
            <br />
            <br />
            <hr id={styles.footer_hr} className={styles.footer__hr} />
            <br />
            <br />
            <div className={styles.footer__text__container}>
              <p>
                <span className={styles.footer__span}>PokerbaaziLive</span>
              </p>
              <p>
                <span className={styles.footer__span2}>
                  Copyright @ Baazi Games Pvt. Ltd.
                </span>
              </p>
              <p>
                <span className={styles.footer__span3}>Follow Us</span>
                <a
                  href="https://www.facebook.com/pokerbaazilive"
                  target="_blank"
                >
                  <span>
                    <img
                      className={styles.fbpng}
                      src="https://icon-library.com/images/facebook-icon-black-png/facebook-icon-black-png-15.jpg"
                    ></img>
                  </span>
                </a>
              </p>
            </div>
          </div>
          <div className={styles.footer__button__container}>
            <a href="#">
              <button className={styles.footer__button}>^</button>
            </a>
          </div>
        </div>
      </footer>

      {/* footer section ended here    */}
    </div>
  );
}
